/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.KhachHgDAO;
import DTO.KhachHgDTO;
import Misc.MiscData;
import Misc.MiscDialog;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class KhachHang extends javax.swing.JFrame {

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
        showTable();
        showDatabase();
    }
    
    private DefaultTableModel model;
    SimpleDateFormat formatdate = new SimpleDateFormat("dd-MM-yyyy");
    
    private void refresh(){
        Makhtxt.setText("");
        Noisinhtxt.setText("");
        Sdttxt.setText("");
        Tenkhtxt.setText("");
        Diachitxt.setText("");
        Namsinhtxt.setText("");
        Emailtxt.setText("");
        buttonGroup1.clearSelection();
    }
    
    private void showTable(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"MÃ KHÁCH HÀNG","TÊN KHÁCH HÀNG","SĐT","ĐỊA CHỈ","NGÀY SINH","NƠI SINH","GIỚI TÍNH","EMAIL"});
        jTable1.setModel(model);
    }
    
    private void showDatabase(){
        try{
            KhachHgDAO dao = new KhachHgDAO();
            List<KhachHgDTO> list = dao.timKHAll();
            model.setRowCount(0);
            for(KhachHgDTO it : list){
                model.addRow(new Object[]{
                    it.getMaKH(),it.getTenKH(),it.getSDT(),it.getDiaChi(),it.getNgaySinh(),it.getNoiSinh(),it.getGioiTinh()==1?"Nam":"Nữ",it.getEmail()
                });
            }
            model.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Makhtxt = new javax.swing.JTextField();
        Tenkhtxt = new javax.swing.JTextField();
        Sdttxt = new javax.swing.JTextField();
        Diachitxt = new javax.swing.JTextField();
        Noisinhtxt = new javax.swing.JTextField();
        Namsinhtxt = new javax.swing.JTextField();
        Emailtxt = new javax.swing.JTextField();
        rbtNam = new javax.swing.JRadioButton();
        rbtNu = new javax.swing.JRadioButton();
        Suabtn = new javax.swing.JButton();
        Thembtn = new javax.swing.JButton();
        Xoabtn = new javax.swing.JButton();
        Huybtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm Khách Hàng");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 321, 733, 317));

        Backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_back_to_20px.png"))); // NOI18N
        Backbtn.setText("Trở về");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 644, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã khách hàng:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ và tên:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("SĐT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Địa chỉ:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 196, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Quê quán:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ngày sinh:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 148, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Giới tính:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 196, -1, -1));
        getContentPane().add(Makhtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 210, -1));
        getContentPane().add(Tenkhtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, -1));
        getContentPane().add(Sdttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 148, 210, -1));
        getContentPane().add(Diachitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 196, 210, 50));
        getContentPane().add(Noisinhtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 70, 200, -1));
        getContentPane().add(Namsinhtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 110, 200, -1));
        getContentPane().add(Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 148, 200, -1));

        buttonGroup1.add(rbtNam);
        rbtNam.setText("Nam");
        getContentPane().add(rbtNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 197, 98, -1));

        buttonGroup1.add(rbtNu);
        rbtNu.setText("Nữ");
        getContentPane().add(rbtNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 197, 98, -1));

        Suabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Suabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_change_20px_1.png"))); // NOI18N
        Suabtn.setText("Sửa");
        Suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuabtnActionPerformed(evt);
            }
        });
        getContentPane().add(Suabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 268, -1, 41));

        Thembtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Thembtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_plus_+_20px.png"))); // NOI18N
        Thembtn.setText("Thêm");
        Thembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThembtnActionPerformed(evt);
            }
        });
        getContentPane().add(Thembtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 268, -1, 41));

        Xoabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Xoabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_minus_20px.png"))); // NOI18N
        Xoabtn.setText("Xóa");
        Xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoabtnActionPerformed(evt);
            }
        });
        getContentPane().add(Xoabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 268, -1, 41));

        Huybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Huybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_new_copy_20px.png"))); // NOI18N
        Huybtn.setText("Làm mới");
        Huybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Huybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 268, -1, 41));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLNV Background.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            Makhtxt.setEnabled(false);
            int row = jTable1.getSelectedRow();
            if(row >=0){
                String id = (String)jTable1.getValueAt(row, 0);
                KhachHgDAO dao = new KhachHgDAO();
                KhachHgDTO kh = dao.timKH(id);
                if(kh != null){
                    Makhtxt.setText(kh.getMaKH());
                    Tenkhtxt.setText(kh.getTenKH());
                    Sdttxt.setText(kh.getSDT());
                    Diachitxt.setText(kh.getDiaChi());
                    rbtNam.setSelected(kh.getGioiTinh()==1?true:false);
                    rbtNu.setSelected(kh.getGioiTinh()==0?true:false);
                    Noisinhtxt.setText(kh.getNoiSinh());
                    Namsinhtxt.setText(formatdate.format(kh.getNgaySinh()));
                    Emailtxt.setText(kh.getEmail());
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        setVisible(false);
        TrangChuKH form = new TrangChuKH();
        form.setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void SuabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Makhtxt, sb, "Vui lòng nhập Mã khách hàng");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn cập nhật lại không?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            KhachHgDTO kh = new KhachHgDTO();
            kh.setMaKH(Makhtxt.getText());
            kh.setTenKH(Tenkhtxt.getText());
            kh.setSDT(Sdttxt.getText());
            kh.setDiaChi(Diachitxt.getText());
            kh.setGioiTinh(rbtNam.isSelected()?1:0);
            kh.setNoiSinh(Noisinhtxt.getText());
            kh.setNgaySinh(formatdate.parse(Namsinhtxt.getText()));
            kh.setEmail(Emailtxt.getText());

            KhachHgDAO khdao = new KhachHgDAO();
            if(khdao.updateKH(kh)){
                MiscDialog.showMessageDialog(null, "Chỉnh sửa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Chỉnh sửa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_SuabtnActionPerformed

    private void ThembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThembtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Makhtxt, sb, "Vui lòng nhập Mã khách hàng");
        MiscData.DataEmty(Tenkhtxt, sb, "Vui lòng nhập Tên khách hàng");
        MiscData.DataEmty(Sdttxt, sb, "Vui lòng nhập SĐT");
        MiscData.DataEmty(Diachitxt, sb, "Vui lòng nhập Địa chỉ");
        MiscData.DataEmty(Noisinhtxt, sb, "Vui lòng nhập Nơi sinh");
        MiscData.DataEmty(Namsinhtxt, sb, "Vui lòng nhập Ngày sinh");
        MiscData.DataEmty(Emailtxt, sb, "Vui lòng nhập Email");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        try{

            KhachHgDTO kh = new KhachHgDTO();
            kh.setMaKH(Makhtxt.getText());
            kh.setTenKH(Tenkhtxt.getText());
            kh.setSDT(Sdttxt.getText());
            kh.setDiaChi(Diachitxt.getText());
            kh.setNgaySinh(formatdate.parse(Namsinhtxt.getText()));
            kh.setNoiSinh(Noisinhtxt.getText());
            kh.setGioiTinh(rbtNam.isSelected()?1:0);
            kh.setEmail(Emailtxt.getText());

            KhachHgDAO dao = new KhachHgDAO();
            if(dao.insertKH(kh)){
                MiscDialog.showMessageDialog(null, "Thêm khách hàng thành công", "Thông báo");
                showDatabase();
                refresh();
            }
            else{
                MiscDialog.showConfirmDialog(null, "Thêm không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
        }
    }//GEN-LAST:event_ThembtnActionPerformed

    private void XoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Makhtxt, sb, "Vui lòng nhập Mã khách hàng");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn xóa Khách hàng?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            KhachHgDTO kh = new KhachHgDTO();
            kh.setMaKH(Makhtxt.getText());
            KhachHgDAO khdao = new KhachHgDAO();
            if(khdao.deleteKH(kh)){
                MiscDialog.showMessageDialog(null, "Xóa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Xóa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_XoabtnActionPerformed

    private void HuybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuybtnActionPerformed
        Makhtxt.setText("");
        Noisinhtxt.setText("");
        Sdttxt.setText("");
        Tenkhtxt.setText("");
        Diachitxt.setText("");
        Namsinhtxt.setText("");
        Emailtxt.setText("");
        buttonGroup1.clearSelection();
        Makhtxt.setEnabled(true);
    }//GEN-LAST:event_HuybtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField Diachitxt;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JButton Huybtn;
    private javax.swing.JTextField Makhtxt;
    private javax.swing.JTextField Namsinhtxt;
    private javax.swing.JTextField Noisinhtxt;
    private javax.swing.JTextField Sdttxt;
    private javax.swing.JButton Suabtn;
    private javax.swing.JTextField Tenkhtxt;
    private javax.swing.JButton Thembtn;
    private javax.swing.JButton Xoabtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    // End of variables declaration//GEN-END:variables
}
