/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import DAO.LoaiSPDAO;
import DTO.LoaiSPDTO;
import Misc.MiscData;
import Misc.MiscDialog;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class LoaiSanPham extends javax.swing.JFrame {

    /**
     * Creates new form LoaiSanPham
     */
    public LoaiSanPham() {
        initComponents();
        showTable();
        showDatabase();
    }
    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Backbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Tenlsptxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Malsptxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Huybtn = new javax.swing.JButton();
        Xoabtn = new javax.swing.JButton();
        Suabtn = new javax.swing.JButton();
        Thembtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm Loại Sản Phẩm");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, 821, 210));

        Backbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_back_to_20px.png"))); // NOI18N
        Backbtn.setText("Trở về");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, 44));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên loại sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã loại sản phẩm:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THÊM LOẠI SẢN PHẨM");

        Huybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Huybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_new_copy_20px.png"))); // NOI18N
        Huybtn.setText("Làm Mới");
        Huybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuybtnActionPerformed(evt);
            }
        });

        Xoabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Xoabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_minus_20px.png"))); // NOI18N
        Xoabtn.setText("Xóa");
        Xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoabtnActionPerformed(evt);
            }
        });

        Suabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Suabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_change_20px_1.png"))); // NOI18N
        Suabtn.setText("Sửa");
        Suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuabtnActionPerformed(evt);
            }
        });

        Thembtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Thembtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_plus_+_20px.png"))); // NOI18N
        Thembtn.setText("Thêm");
        Thembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThembtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(Malsptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(Tenlsptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Thembtn)
                        .addGap(48, 48, 48)
                        .addComponent(Suabtn)
                        .addGap(48, 48, 48)
                        .addComponent(Xoabtn)
                        .addGap(50, 50, 50)
                        .addComponent(Huybtn)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Tenlsptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Malsptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Thembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Huybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThemLSP Background (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ThembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThembtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Malsptxt, sb, "Vui lòng nhập Mã loại sản phẩm");
        MiscData.DataEmty(Tenlsptxt, sb, "Vui lòng nhập Tên loại sản phẩm");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        try{
            LoaiSPDTO lsp = new LoaiSPDTO();
            lsp.setMaLoai(Malsptxt.getText());
            lsp.setTenLoai(Tenlsptxt.getText());

            LoaiSPDAO lspdao = new LoaiSPDAO();
            if(lspdao.insertLSP(lsp)){
                MiscDialog.showMessageDialog(null, "Thêm thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Thêm không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_ThembtnActionPerformed

    private void SuabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Malsptxt, sb, "Vui lòng nhập Mã loại sản phẩm");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn cập nhật lại không?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            LoaiSPDTO lsp = new LoaiSPDTO();
            lsp.setMaLoai(Malsptxt.getText());
            lsp.setTenLoai(Tenlsptxt.getText());

            LoaiSPDAO lspdao = new LoaiSPDAO();
            if(lspdao.updateLSP(lsp)){
                MiscDialog.showMessageDialog(null, "Chỉnh sửa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Chỉnh sửa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_SuabtnActionPerformed

    private void XoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Malsptxt, sb, "Vui lòng nhập Mã loại sản phẩm");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn xóa Loai sản phẩm này không?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            LoaiSPDTO lsp = new LoaiSPDTO();
            lsp.setMaLoai(Malsptxt.getText());
            LoaiSPDAO lspdao = new LoaiSPDAO();
            if(lspdao.deleteLSP(lsp)){
                MiscDialog.showMessageDialog(null, "Xóa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Xóa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_XoabtnActionPerformed

    private void HuybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuybtnActionPerformed
        Malsptxt.setText("");
        Tenlsptxt.setText("");
    }//GEN-LAST:event_HuybtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int row = jTable1.getSelectedRow();
            if(row >=0){
                String id = (String)jTable1.getValueAt(row, 0);
                LoaiSPDAO dao = new LoaiSPDAO();
                LoaiSPDTO ncc = dao.timLSP(id);
                if(ncc != null){
                    Malsptxt.setText(ncc.getMaLoai());
                    Tenlsptxt.setText(ncc.getTenLoai());
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        setVisible(false);
        TrangChuHH form = new TrangChuHH();
        form.setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void showTable(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"MÃ LOẠI SẢN PHẨM","TÊN LOẠI SẢN PHẨM"});
        jTable1.setModel(model);
    }
    private void showDatabase(){
        try{
            LoaiSPDAO dao = new LoaiSPDAO();
            List<LoaiSPDTO> list = dao.timLSPAll();
            model.setRowCount(0);
            for(LoaiSPDTO it : list){
                model.addRow(new Object[]{
                    it.getMaLoai(),it.getTenLoai()
                });
            }
            model.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }
    private void refresh(){
        Malsptxt.setText("");
        Tenlsptxt.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaiSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Huybtn;
    private javax.swing.JTextField Malsptxt;
    private javax.swing.JButton Suabtn;
    private javax.swing.JTextField Tenlsptxt;
    private javax.swing.JButton Thembtn;
    private javax.swing.JButton Xoabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
