/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ChiTietHDDAO;
import DTO.ChiTietHDDTO;
import java.io.File;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Row;
import java.io.*;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFCell;
/**
 *
 * @author ADMIN
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) jTable1.getModel();
        showTable();
        Tong();
    }
    
    private List<ChiTietHDDTO> cthd;
    private DefaultTableModel model;
    
    private void showTable(){
        cthd = new ChiTietHDDAO().timCTHDAll();
        model.setRowCount(0);
        for(ChiTietHDDTO hd : cthd){
            model.addRow(new Object[]{
            jTable1.getRowCount()+1,hd.getMaHD(),hd.getNgayNhap(),hd.getThanhTien()
            });
        }
    }
    
    private void Tong(){
        DecimalFormat x = new DecimalFormat("###,###,###");
        int ThanhTien =0;
        for(int i=0;i<jTable1.getRowCount();i++){
            ThanhTien += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }
        jLabelTongDT.setText("Tổng doanh thu: "+x.format(ThanhTien)+" "+"VND");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Timkiemngaybtn = new javax.swing.JButton();
        jLabelTongDT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TKNgaytxt = new javax.swing.JTextField();
        Huybtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TKMhdtxt = new javax.swing.JTextField();
        Timkiemmabtn = new javax.swing.JButton();
        Xuatbtn = new javax.swing.JButton();
        btnBieuDo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống Kê Doanh Thu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THỐNG KÊ DOANH THU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 18, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã hóa đơn", "Ngày nhập", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 570, 382));

        Timkiemngaybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Timkiemngaybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_find_and_replace_20px.png"))); // NOI18N
        Timkiemngaybtn.setText("Tìm kiếm");
        Timkiemngaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimkiemngaybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Timkiemngaybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 99, -1, 36));

        jLabelTongDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTongDT.setText("Tổng doanh thu:");
        getContentPane().add(jLabelTongDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 610, 310, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nhập ngày:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 106, -1, -1));
        getContentPane().add(TKNgaytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 106, 195, -1));

        Huybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Huybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_new_copy_20px.png"))); // NOI18N
        Huybtn.setText("Làm mới");
        Huybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Huybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 99, -1, 36));

        Backbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_back_to_20px.png"))); // NOI18N
        Backbtn.setText("Trở về");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, -1, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nhập MHD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 160, -1, -1));
        getContentPane().add(TKMhdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 160, 193, -1));

        Timkiemmabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Timkiemmabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_find_and_replace_20px.png"))); // NOI18N
        Timkiemmabtn.setText("Tìm kiếm");
        Timkiemmabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimkiemmabtnActionPerformed(evt);
            }
        });
        getContentPane().add(Timkiemmabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 153, -1, 36));

        Xuatbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Xuatbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_microsoft_excel_20px.png"))); // NOI18N
        Xuatbtn.setText("Xuất file");
        Xuatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Xuatbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 153, -1, 36));

        btnBieuDo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBieuDo.setText("BIỂU ĐỒ");
        btnBieuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBieuDoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBieuDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, 36));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DoanhThu Background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TimkiemngaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimkiemngaybtnActionPerformed
        //        String Date = TKNgaytxt.getText();
        //        if(Date.length()>0){
            //            cthd = new ChiTietHDDAO().timDateCTHD(Date);
            //            model.setRowCount(0);
            //        for(ChiTietHDDTO hd : cthd){
                //            model.addRow(new Object[]{
                    //            jTable1.getRowCount()+1,hd.getMaHD(),hd.getNgayNhap(),hd.getThanhTien()
                    //            });
            //        }
        //        }
        DecimalFormat x = new DecimalFormat("###,###,###");
        String Date = TKNgaytxt.getText();
        int ThanhTien =0;
        if(Date.length()>0){
            cthd = new ChiTietHDDAO().timDateCTHD(Date);
            model.setRowCount(0);
            for(ChiTietHDDTO hd : cthd){
                model.addRow(new Object[]{
                    jTable1.getRowCount()+1,hd.getMaHD(),hd.getNgayNhap(),hd.getThanhTien()
                });
            }
            for(int i=0;i<jTable1.getRowCount();i++){
                ThanhTien += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            jLabelTongDT.setText("Tổng doanh thu: "+x.format(ThanhTien)+" "+"VND");
            TKMhdtxt.setEnabled(false);
        }
    }//GEN-LAST:event_TimkiemngaybtnActionPerformed

    private void HuybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuybtnActionPerformed
        TKNgaytxt.setText("");
        TKNgaytxt.setEnabled(true);
        TKMhdtxt.setText("");
        TKMhdtxt.setEnabled(true);
        showTable();
        Tong();
    }//GEN-LAST:event_HuybtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        setVisible(false);
        TrangChu form = new TrangChu();
        form.setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void TimkiemmabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimkiemmabtnActionPerformed
        //        String Mahd = TKMhdtxt.getText();
        //        if(Mahd.length()>0){
            //            cthd = new ChiTietHDDAO().timMaCTHD(Mahd);
            //            model.setRowCount(0);
            //        for(ChiTietHDDTO hd : cthd){
                //            model.addRow(new Object[]{
                    //            jTable1.getRowCount()+1,hd.getMaHD(),hd.getNgayNhap(),hd.getThanhTien()
                    //            });
            //        }
        //        }
        DecimalFormat x = new DecimalFormat("###,###,###");
        String Mahd = TKMhdtxt.getText();
        int ThanhTien =0;
        if(Mahd.length()>0){
            cthd = new ChiTietHDDAO().timMaCTHD(Mahd);
            model.setRowCount(0);
            for(ChiTietHDDTO hd : cthd){
                model.addRow(new Object[]{
                    jTable1.getRowCount()+1,hd.getMaHD(),hd.getNgayNhap(),hd.getThanhTien()
                });
            }
            for(int i=0;i<jTable1.getRowCount();i++){
                ThanhTien += Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            jLabelTongDT.setText("Tổng doanh thu: "+x.format(ThanhTien)+" "+"VND");
            TKNgaytxt.setEnabled(false);
        }
    }//GEN-LAST:event_TimkiemmabtnActionPerformed

    private void XuatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatbtnActionPerformed
        FileOutputStream out = null;
        try {
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet spreadsheet = workbook.createSheet("Thống kê danh thu");
            HSSFRow row = null;
            HSSFCell cell = null;
            int width = 15; // Where width is number of caracters
            spreadsheet.setDefaultColumnWidth(width);

            row = spreadsheet.createRow((short) 2);// hàng 2
            row.setHeight((short) 300);// độ rộng của hàng
            cell = row.createCell(3, CellType.STRING);// vị trí của cột // cột 3 hàng 2
            cell.setCellValue("THỐNG KÊ DOANH THU");

            row = spreadsheet.createRow((short) 3); // cột 3
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Hóa Đơn");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Ngày Nhập");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Thành Tiền");

            for (int i = 0; i < cthd.size(); i++) {
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 300);
                row.createCell(0).setCellValue(i + 1);
                row.createCell(1).setCellValue(cthd.get(i).getMaHD());
                row.createCell(2).setCellValue(cthd.get(i).getNgayNhap());
                row.createCell(3).setCellValue(cthd.get(i).getThanhTien());
            }
            out = new FileOutputStream(new File("D:\\thongkedanhthu.xls"));
            workbook.write(out);
            out.close();
            workbook.close();
            JOptionPane.showMessageDialog(null,"Xuất file thống kê thành công");

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_XuatbtnActionPerformed

    private void btnBieuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBieuDoActionPerformed
        BieuDoJPanel form = new BieuDoJPanel();
        form.setVisible(true);
    }//GEN-LAST:event_btnBieuDoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Huybtn;
    private javax.swing.JTextField TKMhdtxt;
    private javax.swing.JTextField TKNgaytxt;
    private javax.swing.JButton Timkiemmabtn;
    private javax.swing.JButton Timkiemngaybtn;
    private javax.swing.JButton Xuatbtn;
    private javax.swing.JButton btnBieuDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTongDT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
