/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.LoginDAO;
import DTO.LoginDTO;
import Misc.MiscData;
import Misc.MiscDialog;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class TaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form TaiKhoan
     */
    public TaiKhoan() {
        initComponents();
        showTable();
        showDatabase();
        //initComboboxChucVu();
    }
    
    DefaultTableModel model = new DefaultTableModel();
    
    private void showTable(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID","TÊN ĐĂNG NHẬP","MẬT KHẨU","CHỨC VỤ"});
        jTable1.setModel(model);
    }
    
    private void showDatabase(){
        try{
            LoginDAO dao = new LoginDAO();
            List<LoginDTO> list = dao.timTDNAll();
            model.setRowCount(0);
            for(LoginDTO it : list){
                model.addRow(new Object[]{
                    it.getId(),it.getTenDangNhap(),it.getMatKhau(),it.getChucVu()
                });
            }
            model.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }
    
//    private void initComboboxChucVu() {
//        String sql = "Select VaiTro from Login";
//        try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;instance=MSI\\SQLEXPRESS;database=QuanLySieuThi","sa","123456");
//            PreparedStatement ps = conn.prepareStatement(sql)){
//            ResultSet rs = ps.executeQuery();
//            Chucvucb.removeAllItems();
//            while(rs.next()){
//                Chucvucb.addItem(rs.getString("VaiTro"));
//                //Loaispcb.addItem(rs.getString("TenLoai"));
//            }
//            rs.close();
//            ps.close();
//            conn.close();
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//            MiscDialog.showErrorDialog(null, ex.getMessage(), "Lỗi");
//        }
//    }
    
    private void refresh(){
        Idtxt.setText("");
        Taikhoantxt.setText("");
        Matkhautxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Idtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Taikhoantxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Matkhautxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Chucvucb = new javax.swing.JComboBox<>();
        Thembtn = new javax.swing.JButton();
        Xoabtn = new javax.swing.JButton();
        Suabtn = new javax.swing.JButton();
        Huybtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Quản lý Tài khoản");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 6, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 371, 227));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 88, -1, -1));

        Idtxt.setEnabled(false);
        getContentPane().add(Idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 85, 157, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên tài khoản:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 135, -1, -1));
        getContentPane().add(Taikhoantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 132, 157, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mật khẩu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 180, -1, -1));
        getContentPane().add(Matkhautxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 177, 157, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Chức vụ:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 228, -1, -1));

        Chucvucb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên" }));
        getContentPane().add(Chucvucb, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 225, 114, -1));

        Thembtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Thembtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_plus_+_20px.png"))); // NOI18N
        Thembtn.setText("Thêm");
        Thembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThembtnActionPerformed(evt);
            }
        });
        getContentPane().add(Thembtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 275, -1, 37));

        Xoabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Xoabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_minus_20px.png"))); // NOI18N
        Xoabtn.setText("Xóa");
        Xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoabtnActionPerformed(evt);
            }
        });
        getContentPane().add(Xoabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 275, -1, 37));

        Suabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Suabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_change_20px_1.png"))); // NOI18N
        Suabtn.setText("Sửa");
        Suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuabtnActionPerformed(evt);
            }
        });
        getContentPane().add(Suabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 275, -1, 37));

        Huybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Huybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_new_copy_20px.png"))); // NOI18N
        Huybtn.setText("Làm mới");
        Huybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Huybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 275, -1, 37));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLTK Background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int row = jTable1.getSelectedRow();
            if(row >=0){
                int id = (int)jTable1.getValueAt(row, 0);
                LoginDAO dao = new LoginDAO();
                LoginDTO lg = dao.timTDN(String.valueOf(id));
                if(lg != null){
                    Idtxt.setText(String.valueOf(lg.getId()));
                    Taikhoantxt.setText(lg.getTenDangNhap());
                    Matkhautxt.setText(lg.getMatKhau());
                    Chucvucb.setSelectedItem(lg.getChucVu());
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void ThembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThembtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Taikhoantxt, sb, "Vui lòng nhập Tài khoản");
        MiscData.DataEmty(Matkhautxt, sb, "Vui lòng nhập Mật khẩu");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        try{
            LoginDTO lg = new LoginDTO();
            lg.setTenDangNhap(Taikhoantxt.getText());
            lg.setMatKhau(Matkhautxt.getText());
            lg.setChucVu(Chucvucb.getSelectedItem().toString());

            LoginDAO dao = new LoginDAO();
            if(dao.insertTK(lg)){
                MiscDialog.showMessageDialog(null, "Thêm Tài khoản thành công", "Thông báo");
                showDatabase();
                refresh();
            }
            else{
                MiscDialog.showErrorDialog(null, "Thêm không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
        }
    }//GEN-LAST:event_ThembtnActionPerformed

    private void XoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Idtxt, sb, "Vui lòng nhập Id");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn xóa Tài khoản này không?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            LoginDTO lg = new LoginDTO();
            lg.setId(Integer.valueOf(Idtxt.getText()));
            LoginDAO nvdao = new LoginDAO();
            if(nvdao.deleteTK(lg)){
                MiscDialog.showMessageDialog(null, "Xóa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Xóa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_XoabtnActionPerformed

    private void SuabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Idtxt, sb, "Vui lòng nhập Id");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn cập nhật lại không?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            LoginDTO lg = new LoginDTO();
            lg.setId(Integer.valueOf(Idtxt.getText()));
            lg.setTenDangNhap(Taikhoantxt.getText());
            lg.setMatKhau(Matkhautxt.getText());
            lg.setChucVu(Chucvucb.getSelectedItem().toString());

            LoginDAO lgdao = new LoginDAO();
            if(lgdao.updateTK(lg)){
                MiscDialog.showMessageDialog(null, "Chỉnh sửa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Chỉnh sửa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_SuabtnActionPerformed

    private void HuybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuybtnActionPerformed
        Idtxt.setText("");
        Taikhoantxt.setText("");
        Matkhautxt.setText("");
    }//GEN-LAST:event_HuybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Chucvucb;
    private javax.swing.JButton Huybtn;
    private javax.swing.JTextField Idtxt;
    private javax.swing.JTextField Matkhautxt;
    private javax.swing.JButton Suabtn;
    private javax.swing.JTextField Taikhoantxt;
    private javax.swing.JButton Thembtn;
    private javax.swing.JButton Xoabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
