/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import DAO.LoaiSPDAO;
import DAO.NhCCDAO;
import DAO.SPhamDAO;
import DTO.LoaiSPDTO;
import DTO.SPhamDTO;
import Misc.MiscData;
import Misc.MiscDialog;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class ThemHH extends javax.swing.JFrame {

    /**
     * Creates new form ThemHH
     */
    public ThemHH(){
        initComponents();
        initComboboxLoaiSP();
        //getcbLSP();
        initComboboxNCC();
        showTable();
        showDatabase();
    }
    
    private DefaultTableModel model;
//    LoaiSPDAO lspdao = new LoaiSPDAO();
//    NhCCDAO nccdao = new NhCCDAO();
//    
//    private void getcbLSP(){
//        DefaultComboBoxModel cbModel = (DefaultComboBoxModel) Loaispcb.getModel();
//        for(LoaiSPDTO lsp : lspdao.getALLLSP()){
//            cbModel.addElement(lsp);
//        }
//    }
    
    private void initComboboxLoaiSP() {
        String sql = "Select MaLoai from LoaiSP";
        try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;instance=MSI\\SQLEXPRESS;database=QuanLySieuThi","sa","123456");
            PreparedStatement ps = conn.prepareStatement(sql)){
            ResultSet rs = ps.executeQuery();
            Loaispcb.removeAllItems();
            while(rs.next()){
                Loaispcb.addItem(rs.getString("MaLoai"));
                //Loaispcb.addItem(rs.getString("TenLoai"));
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            MiscDialog.showErrorDialog(null, ex.getMessage(), "Lỗi");
        }
    }
    private void initComboboxNCC() {
        String sql = "Select MaNCC from NhaCungCap";
        try(Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;instance=MSI\\SQLEXPRESS;database=QuanLySieuThi","sa","123456");
            PreparedStatement ps = conn.prepareStatement(sql)){
            ResultSet rs = ps.executeQuery();
            NCCcb.removeAllItems();
            while(rs.next()){
                NCCcb.addItem(rs.getString("MaNCC"));
                //NCCcb.addItem(rs.getString("TenNCC"));
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            MiscDialog.showErrorDialog(null, ex.getMessage(), "Lỗi");
        }
    }
    
    
    
    private void refresh(){
        Masptxt.setText("");
        Tensptxt.setText("");
        Hansudungtxt.setText("");
        Giatientxt.setText("");
        Soluongtxt.setText("");
        Ngaynhaptxt.setText("");
    }
    
    private void showTable(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"MÃ SẢN PHẨM","TÊN SẢN PHẨM","GIÁ TIỀN","SỐ LƯỢNG","HSD","MÃ LOẠI","MÃ NCC","NGÀY NHẬP"});
        jTable1.setModel(model);
    }
    
    private void showDatabase(){
        try{
            SPhamDAO dao = new SPhamDAO();
            List<SPhamDTO> list = dao.timSPAll();
            model.setRowCount(0);
            for(SPhamDTO it : list){
                model.addRow(new Object[]{
                    it.getMaSP(),it.getTenSP(),it.getGiaTien(),it.getSoLuong(),it.getHSD(),it.getMaLoai(),it.getMaNCC(),it.getDate()
                });
            }
            model.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Backbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Loaispcb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NCCcb = new javax.swing.JComboBox<>();
        Hansudungtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Ngaynhaptxt = new javax.swing.JTextField();
        Soluongtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Giatientxt = new javax.swing.JTextField();
        Tensptxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Masptxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Huybtn = new javax.swing.JButton();
        Xoabtn = new javax.swing.JButton();
        Suabtn = new javax.swing.JButton();
        Thembtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm Sản Phẩm");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 328, 790, 306));

        Backbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_back_to_20px.png"))); // NOI18N
        Backbtn.setText("Trở về");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 640, -1, 47));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Loại sản phẩm:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nhà cung cấp:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Hạn sử dụng:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ngày nhập:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Số lượng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Giá tiền:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THÊM SẢN PHẨM");

        Huybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Huybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_new_copy_20px.png"))); // NOI18N
        Huybtn.setText("Làm mới");
        Huybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuybtnActionPerformed(evt);
            }
        });

        Xoabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Xoabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_minus_20px.png"))); // NOI18N
        Xoabtn.setText("Xóa");
        Xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoabtnActionPerformed(evt);
            }
        });

        Suabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Suabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_change_20px_1.png"))); // NOI18N
        Suabtn.setText("Sửa");
        Suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuabtnActionPerformed(evt);
            }
        });

        Thembtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Thembtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_plus_+_20px.png"))); // NOI18N
        Thembtn.setText("Thêm");
        Thembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThembtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(Masptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Loaispcb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(Tensptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22)
                                .addComponent(NCCcb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(48, 48, 48)
                                .addComponent(Giatientxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(Hansudungtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(40, 40, 40)
                                .addComponent(Soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel9)
                                .addGap(42, 42, 42)
                                .addComponent(Ngaynhaptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Thembtn)
                        .addGap(33, 33, 33)
                        .addComponent(Suabtn)
                        .addGap(36, 36, 36)
                        .addComponent(Xoabtn)
                        .addGap(35, 35, 35)
                        .addComponent(Huybtn)
                        .addGap(105, 105, 105))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Masptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Loaispcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Tensptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(NCCcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Giatientxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Hansudungtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Ngaynhaptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Thembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Xoabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Huybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 290));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThemHH Background.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try{
            int row = jTable1.getSelectedRow();
            if(row >=0){
                String id = (String)jTable1.getValueAt(row, 0);
                SPhamDAO dao = new SPhamDAO();
                SPhamDTO sp = dao.timSP(id);
                if(sp != null){
                    Masptxt.setText(sp.getMaSP());
                    Tensptxt.setText(sp.getTenSP());
                    Giatientxt.setText(String.valueOf(sp.getGiaTien()));
                    Soluongtxt.setText(String.valueOf(sp.getSoLuong()));
                    Hansudungtxt.setText(sp.getHSD());
                    Loaispcb.setSelectedItem(sp.getMaLoai());
                    NCCcb.setSelectedItem(sp.getMaNCC());
                    Ngaynhaptxt.setText(formatdate.format(sp.getDate()));
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void SuabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Masptxt, sb, "Vui lòng nhập Mã sản phẩm");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn cập nhật lại không?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            SPhamDTO sp = new SPhamDTO();
            sp.setMaSP(Masptxt.getText());
            sp.setTenSP(Tensptxt.getText());
            sp.setGiaTien(Float.parseFloat(Giatientxt.getText()));
            sp.setHSD(Hansudungtxt.getText());
            sp.setSoLuong(Integer.parseInt(Soluongtxt.getText()));
            sp.setMaNCC(NCCcb.getSelectedItem().toString());
            sp.setMaLoai(Loaispcb.getSelectedItem().toString());
            sp.setDate(formatdate.parse(Ngaynhaptxt.getText()));

            SPhamDAO spdao = new SPhamDAO();
            if(spdao.updateSP(sp)){
                MiscDialog.showMessageDialog(null, "Chỉnh sửa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Chỉnh sửa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_SuabtnActionPerformed

    private void ThembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThembtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Masptxt, sb, "Vui lòng nhập Mã sản phẩm");
        MiscData.DataEmty(Tensptxt, sb, "Vui lòng nhập Tên sản phẩm");
        MiscData.DataEmty(Giatientxt, sb, "Vui lòng nhập Giá tiền");
        MiscData.DataEmty(Soluongtxt, sb, "Vui lòng nhập Số lượng");
        MiscData.DataEmty(Ngaynhaptxt, sb, "Vui lòng nhập ngày");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        try{
            SPhamDTO kh = new SPhamDTO();
            kh.setMaSP(Masptxt.getText());
            kh.setTenSP(Tensptxt.getText());
            kh.setGiaTien(Float.parseFloat(Giatientxt.getText()));
            kh.setSoLuong(Integer.parseInt(Soluongtxt.getText()));
            kh.setHSD(Hansudungtxt.getText());
            kh.setMaLoai(Loaispcb.getSelectedItem().toString());
            kh.setMaNCC(NCCcb.getSelectedItem().toString());
            kh.setDate(formatdate.parse(Ngaynhaptxt.getText()));

            SPhamDAO dao = new SPhamDAO();
            if(dao.insertSP(kh)){
                MiscDialog.showMessageDialog(null, "Thêm Sản phẩm thành công", "Thông báo");
                showDatabase();
                refresh();
            }
            else{
                MiscDialog.showErrorDialog(null, "Thêm không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
        }
    }//GEN-LAST:event_ThembtnActionPerformed

    private void XoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoabtnActionPerformed
        StringBuilder sb = new StringBuilder();
        MiscData.DataEmty(Masptxt, sb, "Vui lòng nhập Mã sản phẩm");
        if(sb.length()>0){
            MiscDialog.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MiscDialog.showConfirmDialog(null, "Bạn có muốn xóa Sản phẩm?", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try{
            SPhamDTO sp = new SPhamDTO();
            sp.setMaSP(Masptxt.getText());
            SPhamDAO nvdao = new SPhamDAO();
            if(nvdao.deleteSP(sp)){
                MiscDialog.showMessageDialog(null, "Xóa thành công", "Thông báo");
                showDatabase();
                refresh();
            }else{
                MiscDialog.showErrorDialog(null, "Xóa không thành công", "Lỗi");
            }
        }catch(Exception e){
            e.printStackTrace();
            MiscDialog.showErrorDialog(null, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_XoabtnActionPerformed

    private void HuybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuybtnActionPerformed
        Masptxt.setText("");
        Tensptxt.setText("");
        Hansudungtxt.setText("");
        Giatientxt.setText("");
        Soluongtxt.setText("");
        Ngaynhaptxt.setText("");
    }//GEN-LAST:event_HuybtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        setVisible(false);
        TrangChuHH form = new TrangChuHH();
        form.setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    SimpleDateFormat formatdate = new SimpleDateFormat("dd-MM-yyyy");
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemHH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField Giatientxt;
    private javax.swing.JTextField Hansudungtxt;
    private javax.swing.JButton Huybtn;
    private javax.swing.JComboBox<String> Loaispcb;
    private javax.swing.JTextField Masptxt;
    private javax.swing.JComboBox<String> NCCcb;
    private javax.swing.JTextField Ngaynhaptxt;
    private javax.swing.JTextField Soluongtxt;
    private javax.swing.JButton Suabtn;
    private javax.swing.JTextField Tensptxt;
    private javax.swing.JButton Thembtn;
    private javax.swing.JButton Xoabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
